"""empty message

Revision ID: e92b67c121f2
Revises: 06d7953bbd3f
Create Date: 2022-04-25 19:45:20.018933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e92b67c121f2'
down_revision = '06d7953bbd3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('whatever', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'whatever')
    # ### end Alembic commands ###
